### ISSUE TITLE
TODO LIST FOR Improvements

### ISSUE THREAD

**Issue by Nikita-Belyakov** [Nikita-Belyakov/GeoInfoNet_Levir_CS_Improvements#1]
- [x] Split test Levir_CS dataset to val/test sets with 500/600 proportions
- [x] Make inference of gin.pth model on a new test set (600 samples), fix F1, IoU stats (torchmetrics)
- [ ] Change training pipeline: add validation step, inplace SGD to AdamW (Ranger21), inplace CELoss to FocalLoss+DiceLoss
- [ ] Make a new inference of upd_gin.pth model on a new test set (600 samples), fix F1, IoU stats (torchmetrics), compare with old stats
- [ ] Add CosineAnnealingWarmRestarts scheduler & soup several models, make inference and compare new stats with old ones
- [ ] Add WeightedRandomSampler to training pipeline, check inference stats, compare with old ones
- [ ] Add new augmentations to training pipeline (kornia + Albumentations), check inference stats, compare with old ones
- [ ] Add smart augmentations to training pipeline: domain adaptation, handmade augmentations aka OBA with snow, check inference stats, compare with old ones
